services:
  app:
    image: itzcrazykns1337/perplexica:main
    build:
      context: .
      dockerfile: app.dockerfile
    environment:
      - SEARXNG_API_URL=http://192.168.1.180:30053
      - DATA_DIR=/home/perplexica
      - NEXT_PUBLIC_API_URL=https://search.nokodo.dev
      - NEXT_PUBLIC_WS_URL=wss://search.nokodo.dev/ws 
    ports:
      - 8888:3000
    volumes:
      - backend-dbstore:/home/perplexica/data
      - uploads:/home/perplexica/uploads
      - ./config.toml:/home/perplexica/config.toml
    restart: unless-stopped

volumes:
  backend-dbstore:
  uploads: